### ISSUE TITLE
WG link on RFC tombstone does not go to working anchor

### ISSUE THREAD

**Issue by alexisannerossi** [rfc-editor/rpcwebsite#31]
The working group link under Source on the metadata tombstone page takes you to the right page, but the anchor does not work. So no matter which WG you click it seems like you always end up on a page about the art WG. (I thought it was going to the wrong page entirely until I scrolled waaaaayyyy down and figured it out.)

To reproduce:

- Go to https://www.rfc-editor.org/info/rfc9131
- Click on int in the Source field (link is https://datatracker.ietf.org/wg/#int/)
- The target page does not scroll to appropriate section
- This seems to be true for all WG links, not just the int link

Potential fix:

- Instead of formatting the link like this: https://datatracker.ietf.org/wg/#int/
- Format the link like this to go to section: https://datatracker.ietf.org/wg#int

**Also:** when you go to the link that works (https://datatracker.ietf.org/wg#int) it rewrites it into a link that doesn't work, so a person can't copy/paste the URL from there and have it work for others.

**Comment by rjsparks** [comment]
Minor tweaks to the terms used above to maybe make this easier to digest.
There are two links in the Source section.

The first (in the example given) is to the 6lo working group about page, and that link seems to be constructed correctly, but it does use an archaic segment. It would be better if it pointed to https://datatracker.ietf.org/wg/6man/about/ rather than  https://datatracker.ietf.org/wg/6man/charter/

The issue reported here is for the second link to the Area (not a WG), and the change proposed would make sense, though it would also be correct (and perhaps preferable) to only remove the trailing slash after the fragment identifier. That is, use https://datatracker.ietf.org/wg/#int instead of https://datatracker.ietf.org/wg/#int/
